name: nuxyoung
description: Appointment system for child with disability

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl:
  flutter_form_builder:
  table_calendar: ^2.2.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_thailand_provinces: ^1.0.1
  firebase_auth: ^0.15.1
  firebase_core:
  # cached_network_image: ^1.1.3
  path_provider:
  http:
  cloud_firestore: ^0.12.11
  shared_preferences: ^0.5.4+8
  video_player: ^0.10.4+1
  # chewie: ^0.9.8+1
  file_picker: ^1.4.3+1
  firebase_database: ^3.1.0
  firebase_storage: ^3.0.8
  scrolling_years_calendar: ^1.2.0
  image_picker: ^0.6.2+1
  flutter_swiper: ^1.1.6
  numberpicker: ^1.1.0
  pull_to_refresh: ^1.5.7
  firebase_messaging: ^6.0.2
  flutter_typeahead: ^1.7.0
  rflutter_alert: ^1.0.3
  flutter_local_notifications: ^0.8.4+3
  provider: ^3.2.0
  gradient_app_bar: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/welcome.png
    - assets/images/welcomehome.png
    - assets/images/13978.png
    - assets/images/dvm.jpg
    - assets/images/dvmcity.gif
    - assets/images/hospital.gif
    - assets/images/regislogo.png
    - assets/images/homewall.png
    - assets/images/a.jpg
    - assets/images/login.png
    - assets/images/message.png
    - assets/images/doc_231.jpg
    - assets/images/profiledoc.png
    - assets/images/555.jpg
    - assets/images/p2.jpg
    - assets/bell.png
    - assets/mypdf.pdf
    - assets/doc.pdf

  fonts:
    - family: Chat
      fonts:
        - asset: assets/fonts/Chat.ttf
